### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by na2hiro** [na2hiro/Kifu-for-JS#83]
These repositories are tightly coupled. If we make a monorepo containing these 3, we'll benefit with easy development and low maintenance cost.

* https://github.com/na2hiro/Shogi.js (library)
* https://github.com/na2hiro/json-kifu-format (library)
* https://github.com/na2hiro/Kifu-for-JS

### Tasks

Required

- [x] Set up caching
- [x] Set up build and lint commands
- [x] Set up test command
- [x] Set up dev mode with automatic rebuilds
- [x] Set up GitHub Actions for
  - [x] branch builds
  - [x] pages
  - [x] publish
    - ref. publishing with Lerna https://link-and-motivation.hatenablog.com/entry/2022/11/16/190305
    - ref. lerna publish lifecycle https://github.com/lerna/lerna/tree/main/libs/commands/publish
- [x] Set up publish command
- [x] Re-enable hooks

Nice to do

- [x] Lift up common tools
  - [x] webpack
  - [x] linting
  - [x] jest

Out of scope
* Fix Shogi.js not to generate .d.ts files, which breaks build later
* Enzyme to testing library
* TSLint to ESLint (shogi.js)

### References
* https://lerna.js.org/docs/getting-started
* How to keep Git history when merging repos https://medium.com/@chris_72272/keeping-git-history-when-converting-multiple-repos-into-a-monorepo-97641744d928
* Husky not working by default. Need to convert https://qiita.com/kyntk/items/bd5488a7f25396aba719

**Comment by na2hiro** [comment]
#84

**Comment by na2hiro** [comment]
This also fixed a bug that examples were broken http://apps.81.la/Kifu-for-JS/examples/example.html
